### ISSUE TITLE
Improving on perfection

### ISSUE THREAD

**Issue by Ebren100** [theHostileNegotiator/KWBandage#1]
First time doing anything on GitHub so do excuse me. 
I'm a big fan of KWBandage and I wanted to let you know there's a typo in the ZOCOMHarvester Experience Levels stuff. It relies on GDIHarvester instead and does not get the Heroic attribute.

As for more important issues: Have you noticed the Skirmish AI using abilities such as EMP grenades before they've cooled down when using this mod? 

Thanks for all your hard work

**Comment by theHostileNegotiator** [comment]
1. ZOCOMHarvester Experience Levels stuff. It relies on GDIHarvester instead and does not get the Heroic attribute.
Left over from EA. This issue will be resolved
2. Have you noticed the Skirmish AI using abilities such as EMP grenades before they've cooled down when using this mod?
Strange, I would of thought the AI would be limited by the Cooldown specified in the Template. I doubt this is something I can fix on my end unfortunately
