### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by Ebren100** [theHostileNegotiator/KWBandage#4]
Your GDI and ST Riflemen are uncrushable - missing crusher info.

Since you made the Saboteur change, I thought I'd mention that Nod Commandos also have directional armour.

I'd really appreciate it if you could tell me how I'd go about importing something that would allow me to change the Skirmish start cash like seen in MpGameRules in the reference KW XMLs, or where I could find information. Typically I'm lost if I'm importing something that you haven't already got in your mod here. The key difference being "global" imports or something

**Comment by theHostileNegotiator** [comment]
WrathEd has a Big viewer (BigView.bat) which you can use and extract the Asset in xml format into an xml file. I use the xml source pack which can be found here https://ppmforums.com/topic-41364/tiberium-wars-kanes-wrath-editing-tools-and-assets-list/ but you have to build some of the stuff fully as WrathEd does not support inheritance and xi:includes. If you are starting out, I would recommend using the BigView method. There is a Discord server for the modding community if you have anymore questions https://discord.gg/TfdcQTn.
